Repository locationtech/jts, pull requests merged in 2022-11, with the labels that each got.

#924 LineSegment.projectionFactor was being recalculated unnecessarily.
  modules/core/src/main/java/org/locationtech/jts/geom/LineSegment.java
Labels: type-improvement

#923 Replace Math.sqrt(x^2+y^2) with Math.hypot(x,y)
  modules/app/src/main/java/org/locationtech/jtstest/testbuilder/ui/style/AWTUtil.java
  modules/app/src/main/java/org/locationtech/jtstest/testbuilder/ui/style/ArrowSegmentStyle.java
  modules/app/src/main/java/org/locationtech/jtstest/testbuilder/ui/style/DataLabelStyle.java
  modules/core/src/main/java/org/locationtech/jts/algorithm/CGAlgorithms.java
  modules/core/src/main/java/org/locationtech/jts/algorithm/Length.java
  modules/core/src/main/java/org/locationtech/jts/algorithm/LineIntersector.java
  modules/core/src/main/java/org/locationtech/jts/algorithm/MinimumBoundingCircle.java
  modules/core/src/main/java/org/locationtech/jts/geom/Coordinate.java
  modules/core/src/main/java/org/locationtech/jts/geom/Envelope.java
  modules/core/src/main/java/org/locationtech/jts/geom/LineSegment.java
  modules/core/src/main/java/org/locationtech/jts/geom/util/AffineTransformation.java
  modules/core/src/main/java/org/locationtech/jts/index/strtree/EnvelopeDistance.java
  modules/core/src/main/java/org/locationtech/jts/math/Vector2D.java
  modules/core/src/main/java/org/locationtech/jts/operation/buffer/OffsetSegmentGenerator.java
  modules/core/src/main/java/org/locationtech/jts/operation/overlay/validate/OffsetPointGenerator.java
  modules/core/src/main/java/org/locationtech/jts/triangulate/quadedge/Vertex.java
  modules/lab/src/main/java/org/locationtech/jtslab/edgeray/EdgeRay.java
Labels: type-improvement

#922 Ensure GeometryFixer does not change coordinate dimension
  modules/core/src/main/java/org/locationtech/jts/algorithm/RobustLineIntersector.java
  modules/core/src/main/java/org/locationtech/jts/noding/NodedSegmentString.java
  modules/core/src/main/java/org/locationtech/jts/noding/SegmentNode.java
  modules/core/src/main/java/org/locationtech/jts/noding/SegmentNodeList.java
  modules/core/src/main/java/org/locationtech/jts/operation/buffer/OffsetCurveBuilder.java
  modules/core/src/test/java/org/locationtech/jts/geom/util/GeometryFixerTest.java
Labels: type-improvement

#925 Fix TopologyPreservingSimplifier to prevent edge-disjoint line collapse
  modules/core/src/main/java/org/locationtech/jts/simplify/TaggedLineStringSimplifier.java
  modules/core/src/test/java/org/locationtech/jts/simplify/TopologyPreservingSimplifierTest.java
  modules/core/src/test/java/test/jts/perf/simplify/TopologyPreservingSimplifierStabilityTest.java
Labels: type-improvement

#927 Improve ConvexHull radial sort robustness
  modules/core/src/main/java/org/locationtech/jts/algorithm/ConvexHull.java
  modules/core/src/test/java/org/locationtech/jts/algorithm/ConvexHullTest.java
Labels: type-bug, jts-core

#931 More robust Delaunay Triangulation frame size heuristic
  modules/core/src/main/java/org/locationtech/jts/triangulate/quadedge/QuadEdgeSubdivision.java
  modules/core/src/test/java/org/locationtech/jts/triangulate/DelaunayTest.java
  modules/core/src/test/java/org/locationtech/jts/triangulate/VoronoiTest.java
Labels: type-bug, jts-core

#936 Deprecate non-functional AffineTransformation point mapping constructor
  modules/core/src/main/java/org/locationtech/jts/geom/util/AffineTransformation.java
Labels: type-cleanup
