Repository locationtech/jts, pull requests merged in 2025-01, with the labels that each got.

#1045 Fix Douglas Peucker simplifier for XYZM coordinates
  modules/core/src/main/java/org/locationtech/jts/simplify/DouglasPeuckerLineSimplifier.java
  modules/core/src/test/java/org/locationtech/jts/simplify/DouglasPeuckerSimplifierTest.java
  modules/core/src/test/java/test/jts/GeometryTestCase.java
Labels: type-improvement

#1107 Fix VWSimplifier coordinate aliasing
  modules/core/src/main/java/org/locationtech/jts/simplify/VWLineSimplifier.java
  modules/core/src/test/java/org/locationtech/jts/simplify/VWSimplifierTest.java
  modules/core/src/test/java/test/jts/GeometryTestCase.java
Labels: type-bug

#1109 Fix OffsetCurve to support mitre joins for polygons
  modules/core/src/main/java/org/locationtech/jts/operation/buffer/OffsetCurve.java
  modules/core/src/test/java/org/locationtech/jts/operation/buffer/OffsetCurveTest.java
Labels: type-improvement

#1112 Add faster MathUtil.hypot function
  modules/app/src/main/java/org/locationtech/jtstest/testbuilder/ui/style/AWTUtil.java
  modules/app/src/main/java/org/locationtech/jtstest/testbuilder/ui/style/ArrowSegmentStyle.java
  modules/app/src/main/java/org/locationtech/jtstest/testbuilder/ui/style/DataLabelStyle.java
  modules/core/src/main/java/org/locationtech/jts/algorithm/CGAlgorithms.java
  modules/core/src/main/java/org/locationtech/jts/algorithm/Length.java
  modules/core/src/main/java/org/locationtech/jts/algorithm/LineIntersector.java
  modules/core/src/main/java/org/locationtech/jts/algorithm/MinimumBoundingCircle.java
  modules/core/src/main/java/org/locationtech/jts/geom/Coordinate.java
  modules/core/src/main/java/org/locationtech/jts/geom/Envelope.java
  modules/core/src/main/java/org/locationtech/jts/geom/LineSegment.java
  modules/core/src/main/java/org/locationtech/jts/geom/util/AffineTransformation.java
  modules/core/src/main/java/org/locationtech/jts/index/strtree/EnvelopeDistance.java
  modules/core/src/main/java/org/locationtech/jts/math/MathUtil.java
  modules/core/src/main/java/org/locationtech/jts/math/Vector2D.java
  modules/core/src/main/java/org/locationtech/jts/operation/buffer/OffsetSegmentGenerator.java
  modules/core/src/main/java/org/locationtech/jts/operation/overlay/validate/OffsetPointGenerator.java
  modules/core/src/main/java/org/locationtech/jts/triangulate/quadedge/Vertex.java
  modules/lab/src/main/java/org/locationtech/jtslab/edgeray/EdgeRay.java
Labels: type-improvement, jts-core

#1111 `LineStringSnapper` Performance Improvement
  modules/core/src/main/java/org/locationtech/jts/algorithm/Distance.java
  modules/core/src/main/java/org/locationtech/jts/geom/Coordinate.java
  modules/core/src/main/java/org/locationtech/jts/operation/overlay/snap/LineStringSnapper.java
Labels: type-improvement, type-perf
